name: "Release"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
env:
  ITCH_USERNAME: joglr97
  ITCH_GAME_ID: my-game-id
jobs:
  tagged-release:
    name: Make Release
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: "Build & Make zip"
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn zip

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: fruit-rush.zip

      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./build/${{ matrix.template }}
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}
          buildNumber: ${{ needs.version.outputs.version_hash }}
