name: Genetate ZIP file

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Build
        run: |
          yarn
          yarn build

      - uses: actions/upload-artifact@v2
        with:
          name: Fruit Rush
          path: dist
